# Generated by Django 3.0.3 on 2020-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('seatno', models.CharField(max_length=50)),
                ('date01', models.CharField(max_length=50)),
                ('date1', models.CharField(max_length=50)),
                ('time01', models.CharField(max_length=50)),
                ('time1', models.CharField(max_length=50)),
                ('emer', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='combine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('nat', models.CharField(max_length=20)),
                ('ste', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=10)),
                ('img', models.ImageField(upload_to='image')),
                ('date0', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=200)),
                ('gname', models.CharField(max_length=200)),
                ('dname', models.CharField(max_length=200)),
                ('emer', models.CharField(max_length=20)),
                ('date1', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='general',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('seatno', models.CharField(max_length=50)),
                ('date01', models.CharField(max_length=50)),
                ('date1', models.CharField(max_length=50)),
                ('time01', models.CharField(max_length=50)),
                ('time1', models.CharField(max_length=50)),
                ('emer', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='icuroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('seatno', models.CharField(max_length=50)),
                ('date01', models.CharField(max_length=50)),
                ('date1', models.CharField(max_length=50)),
                ('time01', models.CharField(max_length=50)),
                ('time1', models.CharField(max_length=50)),
                ('emer', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='iicu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('seatno', models.CharField(max_length=50)),
                ('date01', models.CharField(max_length=50)),
                ('date1', models.CharField(max_length=50)),
                ('time01', models.CharField(max_length=50)),
                ('time1', models.CharField(max_length=50)),
                ('emer', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='register_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('nat', models.CharField(max_length=20)),
                ('ste', models.CharField(max_length=10)),
                ('age', models.IntegerField(max_length=10)),
                ('img', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='sendreport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date0', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=200)),
                ('gname', models.CharField(max_length=200)),
                ('dname', models.CharField(max_length=200)),
                ('emer', models.CharField(max_length=20)),
                ('date1', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=10)),
            ],
        ),
    ]
